Create Database QL
use QL
CREATE TABLE NHOMNV (
    IDNHOM INT IDENTITY PRIMARY KEY,
	IDNV INT,
    TenNhom NVARCHAR(255),
);
GO
CREATE TABLE NHANVIEN (
    IDNV INT IDENTITY PRIMARY KEY,
	IDNHOM INT not null,
    Hoten NVARCHAR(255),
    Address nvarchar(255),
	Sdt int, 
	
);
GO
CREATE TABLE CA(
	IDNV		INT IDENTITY PRIMARY KEY,
	Luong			money not null,
	Soca			time not null,-- So ca
);
GO
Create table TAIKHOAN(
	IDNV		INT IDENTITY PRIMARY KEY,
	Username	nvarchar(50) not null,
	Password	nvarchar(50) not null,
);
GO
CREATE TABLE KHACHHANG (
    IDKH INT IDENTITY PRIMARY KEY,
    Hoten NVARCHAR(255),
    Address NVARCHAR(255),
	Sdt INT,
	Email NVARCHAR(255),
);
GO
CREATE TABLE HANG
(
	IDH INT IDENTITY PRIMARY KEY,-- id hang
	TenHang NVARCHAR(100) NOT NULL ,
	Nuoc NVARCHAR(100) NOT NULL 
)
GO
CREATE TABLE DANHMUC
(
	IDDM INT IDENTITY PRIMARY KEY,
	TenDM NVARCHAR(100) NOT NULL,
)
GO
CREATE TABLE SANPHAM
(
	IDSP INT IDENTITY PRIMARY KEY, -- ID sanpham
	TenSP NVARCHAR(100) NOT NULL ,
	IDDM INT NOT NULL,--ID danh mục
	Gia FLOAT NOT NULL DEFAULT 0,
	Kichthuoc NVARCHAR(100),
	Trongluong NVARCHAR(100),
	IDBH NVARCHAR(100),--ID bảo hành
	IDH INT NOT NULL,
)
GO
CREATE TABLE HOADON
(
	IDHD INT IDENTITY PRIMARY KEY,
	Ngay DATE NOT NULL DEFAULT GETDATE(),-- ngay lap hoa don
	IDKH INT NOT NULL,
	TONG INT NOT NULL,
	NVBH NVARCHAR, 
	NVGH NVARCHAR, 
	Address nvarchar(255), -- dia chi giao hang
)
GO
CREATE TABLE CTHD
(
	IDCTHD INT IDENTITY PRIMARY KEY,
	IDHD INT NOT NULL,
	IDSP INT NOT NULL,
	SL INT NOT NULL,
	Dongia int NOT NULL
)
GO
