Create Database QL
use QL
CREATE TABLE NHOMNV (
    IDNHOM INT IDENTITY PRIMARY KEY,
	IDNV INT not null,
    TenNhom NVARCHAR(255),
);
GO
CREATE TABLE NHANVIEN (
    IDNV INT IDENTITY PRIMARY KEY,
	IDNHOM INT not null,
    Hoten NVARCHAR(255),
    Address nvarchar(255),
	Sdt int, 

	 CONSTRAINT fk_id_nhom
   FOREIGN KEY (IDNHOM)
   REFERENCES NHOMNV (IDNHOM)
);

CREATE TABLE CA(
	IDNV		INT IDENTITY PRIMARY KEY,
	Luong			money not null,
	Soca			time not null,-- So ca
	CONSTRAINT fk_id_nv
   FOREIGN KEY (IDNV)
   REFERENCES NHANVIEN (IDNV)
);

GO
Create table TAIKHOAN(
	IDNV		INT IDENTITY PRIMARY KEY,
	Username	nvarchar(50) not null,
	Password	nvarchar(50) not null,
	CONSTRAINT fk_id_nvtk
   FOREIGN KEY (IDNV)
   REFERENCES NHANVIEN (IDNV)
);

GO
CREATE TABLE KHACHHANG (
    IDKH INT IDENTITY PRIMARY KEY,
    Hoten NVARCHAR(255),
    Address NVARCHAR(255),
	Sdt INT,
	Email NVARCHAR(255),
);
GO
CREATE TABLE HANG
(
	IDH INT IDENTITY PRIMARY KEY,-- id hang
	TenHang NVARCHAR(100) NOT NULL ,
	Nuoc NVARCHAR(100) NOT NULL 

)
GO
CREATE TABLE DANHMUC
(
	IDDM INT IDENTITY PRIMARY KEY,
	TenDM NVARCHAR(100) NOT NULL,
)
GO
CREATE TABLE SANPHAM
(
	IDSP INT IDENTITY PRIMARY KEY, -- ID sanpham
	TenSP NVARCHAR(100) NOT NULL ,
	IDDM INT NOT NULL,--ID danh mục
	Gia FLOAT NOT NULL DEFAULT 0,
	Kichthuoc NVARCHAR(100),
	Trongluong NVARCHAR(100),
	IDBH NVARCHAR(100),--ID bảo hành
	IDH INT NOT NULL,
	CONSTRAINT fk_id_dm
   FOREIGN KEY (IDDM)
   REFERENCES DANHMUC (IDDM),

   CONSTRAINT fk_id_hang
   FOREIGN KEY (IDH)
   REFERENCES HANG (IDH)
)
GO
drop table SANPHAM
CREATE TABLE HOADON
(
	IDHD INT IDENTITY PRIMARY KEY,
	Ngay DATE NOT NULL DEFAULT GETDATE(),-- ngay lap hoa don
	IDKH INT NOT NULL,
	TONG INT NOT NULL,
	IDSP INT NOT NULL,
	Address nvarchar(255), -- dia chi giao hang
	CONSTRAINT fk_id_sphd
   FOREIGN KEY (IDSP)
   REFERENCES SANPHAM (IDSP)
)
GO
drop table HOADON
CREATE TABLE CTHD
(
	IDCTHD INT IDENTITY PRIMARY KEY,
	IDHD INT NOT NULL,
	IDSP INT NOT NULL,
	SL INT NOT NULL,
	IDNV int not null, 
	Dongia int NOT NULL,
	CONSTRAINT fk_id_cthd
   FOREIGN KEY (IDHD)
   REFERENCES HOADON (IDHD),
   	CONSTRAINT fk_id_nvbh
   FOREIGN KEY (IDNV)
   REFERENCES NHANVIEN (IDNV)
)
GO
drop table CTHD